### ISSUE TITLE
Unable to migrate multiple tenants at once when using MySQL

### ISSUE THREAD

**Issue by joeyramone76** [archtechx/tenancy#87] opened 2019-08-12 15:23 UTC
Hi,
 I've write a CRUD controller to manage tenants.
After the creation phase I try to migrate database calling the related artisan command in this way:
`\Artisan::call('tenants:migrate', [
        '--tenants' => [$tenant['uuid']]
      ]);`
but the process fail with an exception

> Symfony \ Component \ Console \ Exception \ CommandNotFoundException
> The command "tenants:migrate" does not exist.

Then to resolve this issue I've clone the command in the App\Console\Commands directory.
When I run the creation process from controller the tenants()->create('sub.domain') command create the tenant and create the database but fail running the migration with this exception

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenant51fc8900-bd14-11e9-812f-bf18d2921640.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)`

I noticed that the problem occur also when I run the migration for all tenants from the terminal
`php artisan tenants:migrate
Tenant: 0263c840-ba6c-11e9-801a-a932495b9d33 (marco.itplog.com)
Nothing to migrate.
Tenant: dabfa100-bce9-11e9-8818-c51ed3718fe9 (umb.itplog.com)

   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenantdabfa100-bce9-11e9-8818-c51ed3718fe9.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)

  at /home/vagrant/Code/rat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tenantdabfa100-bce9-11e9-8818-c51ed3718fe9.migrations' doesn't exist")
      /home/vagrant/Code/rat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326

  2   PDO::prepare("select `migration` from `migrations` order by `batch` asc, `migration` asc")
      /home/vagrant/Code/rat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326

  Please use the argument -v to see more details.`
 
But no errors when I run from terminal the single tenant migration
` php artisan tenants:migrate --tenants=dabfa100-bce9-11e9-8818-c51ed3718fe9
Tenant: dabfa100-bce9-11e9-8818-c51ed3718fe9 (umb.itplog.com)
Migration table created successfully.
`

How can I resolve this blocking issue?

Thanks

**Comment by stancl** [comment] 2019-08-12 15:43
Hi.

Strange issue. I can't reproduce this. `php artisan tenants:migrate` works ok for me with multiple tenants:

```php
php artisan tenants:migrate
Tenant: 19a6f290-bd17-11e9-8021-e1ff25cbbce3 (bar.localhost)
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.15 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.16 seconds)
Tenant: 17fac0f0-bd17-11e9-8be3-0f5e569a5075 (foo.localhost)
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.19 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.17 seconds)
```

What version are you using? Try running `composer update`.

Can you try reproducing this in a fresh Laravel install?

**Comment by joeyramone76** [comment] 2019-08-12 16:27
Hi.
 I try to run composer update and let you know.
Thanks

**Comment by joeyramone76** [comment] 2019-08-12 16:32
Hi.
 same issue when run  `php artisan tenants:migrate`.
I can try with a fresh laravel installation and let you know.

**Comment by joeyramone76** [comment] 2019-08-12 17:52
Hi,
 I've also tried with a fresh 5.8 laravel installation, followed all the steps to install and configure stancl/tenancy but after tenant creation no way to migrate database from code and from terminal.

What could I check?

**Comment by stancl** [comment] 2019-08-12 18:20
> but after tenant creation no way to migrate database from code and from terminal.

Did you move the migrations to `migrations/tenant`?

**Comment by joeyramone76** [comment] 2019-08-12 18:31
yes I do. the strange thing is that if I run a single tenant migration the operation complete successfully...

what does this following instruction do? 
`$this->input->setOption('database', 'tenant');`

could it be related to the error?

**Comment by stancl** [comment] 2019-08-12 18:37
> I've also tried with a fresh 5.8 laravel installation, followed all the steps to install and configure stancl/tenancy but after tenant creation no way to migrate database from code and from terminal.

> the strange thing is that if I run a single tenant migration the operation complete successfully

Can you elaborate on this? Does running the migrations using `--tenant=oneTenantsUuid` work but using no arguments (`php artisan tenants:migarte`) does not work?

> `$this->input->setOption('database', 'tenant');`

This just sets the `--database` option (for the parent object) to `'tenant'`.

**Comment by joeyramone76** [comment] 2019-08-12 18:49
> Can you elaborate on this? Does running the migrations using `--tenant=oneTenantsUuid` work but using no arguments (`php artisan tenants:migarte`) does not work?

Right! if I run no arguments (run migration for all tenants) the migration don't work:

`php artisan tenants:migrate
Tenant: 37a7fe00-bd28-11e9-964d-31c9699a80ca (umberto.certtool.local)
Nothing to migrate.
Tenant: a7b5f290-bd29-11e9-9933-bdb5d031237e (admin.certtool.local)
   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_a7b5f290-bd29-11e9-9933-bdb5d031237e.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)
  at /home/vagrant/Code/certRatingEvaluationTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 
  Exception trace:
  1   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_a7b5f290-bd29-11e9-9933-bdb5d031237e.migrations' doesn't exist")     /home/vagrant/Code/certRatingEvaluationTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326
  2   PDO::prepare("select `migration` from `migrations` order by `batch` asc, `migration` asc")     /home/vagrant/Code/certRatingEvaluationTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326` 

If i run the migration for one tenant the migration work:
`php artisan tenants:migrate --tenants=a7b5f290-bd29-11e9-9933-bdb5d031237e
Tenant: a7b5f290-bd29-11e9-9933-bdb5d031237e (admin.certtool.local)
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.08 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.1 seconds)
`

> This just sets the --database option (for the parent object) to 'tenant'.

ah ok! I thought it was the database connection: if i change 'tenant' value with 'mysql' the error wont occurs but no migrations run

**Comment by stancl** [comment] 2019-08-12 18:59
`\Artisan::call('tenants:migrate')` works without the `--tenants` option?

Seems like the issue is just in running the migrations for multiple tenants. I cannot reproduce this though.

Could you create a repository with the code & steps (like `tenant()->create('admin.certtool.local')`) necessary to reproduce this?

**Comment by joeyramone76** [comment] 2019-08-12 20:06
Actually, from code, I run the single tenant migration, but the migration fails; this is the code:

```php
$basedomain = config('tenancy.exempt_domains');
$subdomain = $request->get('domain');
$tenant=tenant()->create($subdomain.'.'.$basedomain[0]);
\Artisan::call('tenants:migrate', [
  '--tenants' => [$tenant['uuid']]
]);
```

The migration fails also with this code:

```php
$basedomain = config('tenancy.exempt_domains');
$subdomain = $request->get('domain');
$tenant=tenant()->create($subdomain.'.'.$basedomain[0]);
\Artisan::call('tenants:migrate');
 ```

The strange issue is that seem to be not a my code problem because the issue also happens from terminal following your installation/configuration instruction.

You can try to reproduce following this steps:

- create a fresh laravel project
- install and configure tenancy; 
- this is my configuration in tenancy.php

```php
return [
    'storage_driver' => 'Stancl\Tenancy\StorageDrivers\RedisStorageDriver',
    'tenant_route_namespace' => 'App\Http\Controllers',
    'exempt_domains' => [
        // 'localhost',
        'certtool.local'
    ],
    'database' => [
        'based_on' => 'mysql',
        'prefix' => 'cert_',
        'suffix' => '',
    ],
    'redis' => [
        'tenancy' => false,
        'prefix_base' => 'cert_',
        'prefixed_connections' => [
            'default',
            'cache',
        ],
    ],
    'cache' => [
        'tag_base' => 'cert_',
    ],
    'filesystem' => [
        'suffix_base' => 'cert_',
        // Disks which should be suffixed with the suffix_base + tenant UUID.
        'disks' => [
            'local',
            'public',
            // 's3',
        ],
        'root_override' => [
            // Disks whose roots should be overriden after storage_path() is suffixed.
            'local' => '%storage_path%/app/',
            'public' => '%storage_path%/app/public/',
        ],
    ],
    'database_managers' => [
        'sqlite' => 'Stancl\Tenancy\TenantDatabaseManagers\SQLiteDatabaseManager',
        'mysql' => 'Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager',
        'pgsql' => 'Stancl\Tenancy\TenantDatabaseManagers\PostgreSQLDatabaseManager',
    ],
    'queue_database_creation' => false,
    'queue_database_deletion' => false,
];
```

- this the database.php redis config:
```
'redis' => [
        'client' => env('REDIS_CLIENT', 'predis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'predis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_CACHE_DB', 1),
        ],

        'tenancy' => [
            'host' => env('TENANCY_REDIS_HOST', '127.0.0.1'),
            'password' => env('TENANCY_REDIS_PASSWORD', null),
            'port' => env('TENANCY_REDIS_PORT', 6379),
            'database' => env('TENANCY_REDIS_DB', 4),
        ],

    ],
```

- from tinker create almost 2 or 3 tenants
- exit tinker
- run migration for all tenants: php artisan tenants:migrate
- for me, the first migration work, the migration for the second tenant fails with this exception:
```
php artisan tenants:migrate
Tenant: 21ea9740-bd3c-11e9-8731-f7fd780bc047 (subdom3.certtool.local)
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.09 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.13 seconds)
Tenant: 1bc61620-bd3c-11e9-8d98-0d9d9752be9f (subdom1.certtool.local)
   Illuminate\Database\QueryException  : SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_1bc61620-bd3c-11e9-8d98-0d9d9752be9f.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)
  at /home/vagrant/Code/certTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 
  Exception trace:
  1   PDOException::("SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_1bc61620-bd3c-11e9-8d98-0d9d9752be9f.migrations' doesn't exist")      /home/vagrant/Code/certTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326
  2   PDO::prepare("select `migration` from `migrations` order by `batch` asc, `migration` asc")      /home/vagrant/Code/certTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326
  Please use the argument -v to see more details.
```

Let me know if it's all clear

**Comment by joeyramone76** [comment] 2019-08-13 11:33
Hi,
 after some debugging I think I found where the error occur but I don't know how to resolve the issue; probably the laravel migrator makes the repository exists verification to the previous tenant connection (as you can see from the logs) then the "migrations" table is not created because already exist on previous tenant database.  

```php
`[2019-08-13 11:19:20] local.DEBUG: Tenant: 1f7d2b20-bd3c-11e9-8fd7-0919373992d8 (subdom2.certtool.local) `
 
`[2019-08-13 11:19:20] local.ALERT: Tenant Database Manager - Database Name=>cert_1f7d2b20-bd3c-11e9-8fd7-0919373992d8  `

`[2019-08-13 11:19:20] local.ALERT: --->MigrateCommand Handle()  `

`[2019-08-13 11:19:20] local.ALERT: --->MigrateCommand Handle() call prepareDatabase() - try to Prepare DB  `

`[2019-08-13 11:19:20] local.DEBUG: --->MigrateCommand prepareDatabase() - SetConnection==>tenant  `

`[2019-08-13 11:19:20] local.ALERT: --->MigrateCommand prepareDatabase() - Prepare DB==>tenant  `
`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository GetConnection=>tenant  `

`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository GetConnection=>tenant ` 

`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository repositoryExists=>cert_1f7d2b20-bd3c-11e9-8fd7-0919373992d8  `

`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository GetConnection=>tenant  `

`[2019-08-13 11:19:20] local.DEBUG: Tenant: cff2f3f0-bd9f-11e9-b65c-fb673a51d1aa (more.certtool.local)  `

`[2019-08-13 11:19:20] local.ALERT: Tenant Database Manager - Database Name=>cert_cff2f3f0-bd9f-11e9-b65c-fb673a51d1aa  `

`[2019-08-13 11:19:20] local.ALERT: --->MigrateCommand Handle()  `

`[2019-08-13 11:19:20] local.ALERT: --->MigrateCommand Handle() call prepareDatabase() - try to Prepare DB  `

`[2019-08-13 11:19:20] local.DEBUG: --->MigrateCommand prepareDatabase() - SetConnection==>tenant  `

`[2019-08-13 11:19:20] local.ALERT: --->MigrateCommand prepareDatabase() - Prepare DB==>tenant  `

`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository GetConnection=>tenant  `

`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository GetConnection=>tenant  `

`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository repositoryExists=>cert_1f7d2b20-bd3c-11e9-8fd7-0919373992d8  `

`[2019-08-13 11:19:20] local.ALERT: DatabaseMigrationRepository GetConnection=>tenant ` 

`[2019-08-13 11:19:20] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_cff2f3f0-bd9f-11e9-b65c-fb673a51d1aa.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)`
` {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_cff2f3f0-bd9f-11e9-b65c-fb673a51d1aa.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc) at /home/vagrant/Code/DCS/certRatingEvaluationTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_cff2f3f0-bd9f-11e9-b65c-fb673a51d1aa.migrations' doesn't exist at /home/vagrant/Code/DCS/certRatingEvaluationTool/vendor/laravel/framework/src/Illuminate/Database/Connection.php:326)
[stacktrace]`
```

**Comment by stancl** [comment] 2019-08-13 12:01
When I said that it works for me, I did all of the steps you described to reproduce this.

It would help me a lot if you could create a GitHub repository with a Laravel install that reproduces this.

Thanks for debugging that, sounds like it might be the cause of it, but to verify that I need to get this error "working" on my computer.

**Comment by joeyramone76** [comment] 2019-08-13 12:34
Hi.
ok i didn't understand. I prepare it as soon as possible.

**Comment by joeyramone76** [comment] 2019-08-13 13:13
here the fresh laravel repository where I install tenancy 
https://github.com/joeyramone76/tenant

Let me know

**Comment by stancl** [comment] 2019-08-13 13:47
Can you try switching the database driver to SQLite?

- `DB_CONNECTION=sqlite` in .env
- `DB_DATABASE=database/foo.sqlite` in .env
- create empty `foo.sqlite` file in `database` directory
- set `tenancy.database.based_on` to `sqlite`.

I used SQLite in that repository and it works for me:

```
➜ php artisan tinker
Psy Shell v0.9.9 (PHP 7.2.19-0ubuntu0.19.04.1 — cli) by Justin Hileman
>>> tenant()->create('foo.localhost')
=> [
     "uuid" => "7679eae0-bdd0-11e9-817b-6569496d0a36",
     "domain" => "foo.localhost",
   ]
>>> tenant()->create('bar.localhost')
=> [
     "uuid" => "78c7db30-bdd0-11e9-a34e-f1d1326ec10b",
     "domain" => "bar.localhost",
   ]
>>> ^D
Exit:  Ctrl+D
➜ php artisan tenants:migrate
Tenant: 78c7db30-bdd0-11e9-a34e-f1d1326ec10b (bar.localhost)
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.13 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.14 seconds)
Tenant: 7679eae0-bdd0-11e9-817b-6569496d0a36 (foo.localhost)
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.15 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.15 seconds)
```

So I guess the issue is MySQL-specific? I'll try to reproduce it with MySQL.

**Comment by joeyramone76** [comment] 2019-08-13 14:29
oh yes it's right! the issue is MYSQL-specific. I try with SQLite and no errors when migrate!

**Comment by stancl** [comment] 2019-08-13 14:41
Thanks for reporting this. I will take a look at it.

Does migrating a single tenant using code work for you?

```php
\Artisan::call('tenants:migrate', ['--tenants' => [$tenant['uuid']]);
```

**Comment by joeyramone76** [comment] 2019-08-13 14:58
Calling this command from code (and using MySQL) fail with this exception
`Symfony \ Component \ Console \ Exception \ CommandNotFoundException
The command "tenants:migrate" does not exist.`
To resolve this issue I had to clone the command in the App\Console\Commands directory and change some code part (I had to reference the migrator in this way: `$migrator=app('migrator');`) then when execute the code the migrations fails because the `DatabaseMigrationRepository->repositoryExists()` function try to verify the actual logged tenant, despite having passed the created tenant UUID
this is the part of code in the controller:
`  $basedomain = config('tenancy.exempt_domains');`
      `$subdomain = $request->get('domain');`
      `$tenant=tenant()->create($subdomain.'.'.$basedomain[0]);`

     ` \Artisan::call('tenant:migrate', [
        '--tenants' => [$tenant['uuid']]
      ]);`

**Comment by stancl** [comment] 2019-08-13 15:02
Does `Artisan::call('tenants:migrate')` work in tinker?

```php
>>> \Artisan::call('tenants:migrate')
=> 0
>>> \Artisan::output()
=> """
   Tenant: 78c7db30-bdd0-11e9-a34e-f1d1326ec10b (bar.localhost)\n
   Nothing to migrate.\n
   Tenant: 7679eae0-bdd0-11e9-817b-6569496d0a36 (foo.localhost)\n
   Nothing to migrate.\n
   """
```

Also note that `\Artisan::call('tenant:migrate', [` should be `tenants:migrate`.

**Comment by joeyramone76** [comment] 2019-08-13 15:09
> ```
> \Artisan::call('tenants:migrate')
> ```

No don't work for me in tinker: same issue

> \Artisan::call('tenants:migrate')
> Illuminate/Database/QueryException with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cert_22246e40-bd2c-11e9-a5f0-db323101a441.migrations' doesn't exist (SQL: select `migration` from `migrations` order by `batch` asc, `migration` asc)'

> Also note that \Artisan::call('tenant:migrate', [ should be tenants:migrate.
tenant:migrate is the cloned command name

**Comment by stancl** [comment] 2019-08-13 15:12
Right, but the command is found. If you call it in your code, it doesn't find the command?

**Comment by joeyramone76** [comment] 2019-08-13 15:18
If I call `\Artisan::call('tenants:migrate', ['--tenants' => [$tenant['uuid']]);` from controller I have the  command not found exception.
The cloned command (tenant:migrate) called from the code is executed but fails the migration.

**Comment by stancl** [comment] 2019-08-13 15:22
Thanks. I can reproduce that in a fresh Laravel install.

**Comment by joeyramone76** [comment] 2019-08-13 15:30
OK perfect. Let me know if I can help you with other tests or check other code

**Comment by stancl** [comment] 2019-08-13 15:44
Can I ask you to run 

```php
\Artisan::call('migrate');
dd(\Artisan::output());
```

in a fresh Laravel install with MySQL, like this:

```php
Route::get('/', function () {
    \Artisan::call('migrate');
    dd(\Artisan::output());
    return view('welcome');
});
```

I have a suspicion that running even non-tenant migrations outside console will fail.

**Comment by joeyramone76** [comment] 2019-08-13 15:56
I have to put 

> Can I ask you to run
> 
> ```
> \Artisan::call('migrate');
> dd(\Artisan::output());
> ```
> 
> in a fresh Laravel install with MySQL, like this:
> 
> ```
> Route::get('/', function () {
>     \Artisan::call('migrate');
>     dd(\Artisan::output());
>     return view('welcome');
> });
> ```

I have to put this in routes/web.php right? or in tenant.php?

**Comment by joeyramone76** [comment] 2019-08-13 15:58
ok I have put the route in web.php and from tenant.local the migration works; this is the output
`"""
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table (0.52 seconds)
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table (0.1 seconds)
"""`

**Comment by stancl** [comment] 2019-08-17 13:29
This should be fixed now.

https://github.com/stancl/tenancy/commit/be077ae73c3be668e5ce07d462d1e9336e57dc2a

**Closed as completed by stancl** 2019-08-17 13:29 UTC
Labels: bug, support
