### ISSUE TITLE
@can uses central DB in tenant app

### ISSUE THREAD

**Issue by drfraker** [archtechx/tenancy#230] opened 2019-11-20 20:15 UTC
I'm trying to implement this package: https://docs.spatie.be/laravel-permission/v3/installation-laravel/ and I'm running into some problems. Anyone successfully implement this? The error I get is:
```
Illuminate\Contracts\Container\BindingResolutionException
Target class [permission] does not exist.
```

Here is the code that is in tenant.php

```

 Route::group(['middleware' => ['permission:view all properties'],], function () {
            Route::get('properties', 'PropertiesController@index')->name('properties.index');
            Route::get('properties/create', 'PropertiesController@create')->name('properties.create');
            Route::get('properties/{property}/edit', 'PropertiesController@edit')->name('properties.edit');
            Route::put('properties/{property}', 'PropertiesController@update')->name('properties.update');
        });
```

**Comment by stancl** [comment] 2019-11-20 20:27
Is there an issue only with middleware? Everything else works okay?

Moving the migration file is all that's needed to make roles & permissions work in tinker.
```sh
composer require spatie/laravel-permission
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"\n
mv database/migrations/2019_11_20_201843_create_permission_tables.php database/migrations/tenant
art tenants:migrate
php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"\n
```

I plan on adding docs for Permissions & Media Library integration before 2.3.0.

**Comment by drbyte** [comment] 2019-11-20 20:29
@drfraker Did you enable the middleware in your app? 
https://docs.spatie.be/laravel-permission/v3/basic-usage/middleware/

**Comment by stancl** [comment] 2019-11-20 20:31
@drbyte I assume he needs to add the middleware to the `'tenancy'` group (which needs to be added to `$routeMiddleware`)?

**Comment by stancl** [comment] 2019-11-20 20:31
Actually, no. `'tenancy'` is based on `'web'` so it should work.

**Comment by drfraker** [comment] 2019-11-20 22:53
Not sure how I missed that middleware registration in the docs. Ugh. There's 3 hours I'll never get back. Thanks @stancl and @drbyte  You guys rock!

**Comment by stancl** [comment] 2019-11-21 13:44
@drfraker Does everything work now? I'd love to document integrating with these popular packages - the integration process is usually very simple - but it's very time consuming for me to do this with packages I never used and first need to learn.

**Comment by QuiKhung** [comment] 2019-11-26 04:04
I need you help about Spatie permission, it's conflict between system domain and tenant domain when i use @can('name-permission') of Spatie permission package.

**Comment by stancl** [comment] 2019-11-26 13:10
Can you elaborate @QuiKhung? What conflict?

**Comment by dathi** [comment] 2019-11-28 09:41
I have same issue with Spatie permission. 

**Issue:**
When I set permission role in the system domain, it also affects to tenant domains and vice versus. This is not expected behavior. I want to seperate roles of system domain and tenant domains. 

This is what I did so far:
- Setup multiple databases, 1 system database, 2 databases for 2 tenants.
- In every database, I have spatie's role/permisison tables.
- On the blade views, I use @can to check permisisons to show/hide the web components. 

Did I do anything wrong or I need to check/config?

**Comment by stancl** [comment] 2019-11-28 16:04
Hmm, that's strange. Do you think you could share a repository that has this issue with me?

**Comment by stancl** [comment] 2019-11-28 16:14
(Reopening this so that it's visible in the 2.3.0 milestone.)

**Comment by dathi** [comment] 2019-12-10 03:16
Hi @stancl sorry for late response. Sorry I cannot share the repo due to policy. However, we created a sample project to reproduce this issue below.

https://github.com/anhtuanst1/demo-tenancy

**Comment by stancl** [comment] 2019-12-10 15:18
@dathi Thanks a lot for that! What exactly should I look for? Where in the code is the issue? `@can` directives in Blade templates?

**Comment by dathi** [comment] 2019-12-11 02:44
@stancl Thanks for response. Below are the scenario.

I have:
- Root site and Tenant site have separate databases.
- Root: has "super admin" role with full permissions. 
- Tenant: has "system admin" role with full permisisons in tenant.

I do:
- As super admin, I change permission (e.g: uncheck permission Add User). 

Expect:
- No affect to permission of system admin in tenant

Actual:
- Permission of system admin in tenant get changes and vice versus. Although tenant's database no change ("Add User" permisison still checked in tenant's database)

I use @can to check permission in file resources/views/home.blade.php

I think I missed something in configuration in tenant. 

Something like this link https://tenancy.dev/docs/hyn/5.4/spatie-laravel-permission

Thi.

**Comment by coding-sunshine** [comment] 2019-12-25 07:29
I kind of face same issue with Spatie permissions, I have a similar setup where the main app have permissions tables as well as the tenants. When I change variable migrate_after_creation in tenancy.php config to true, it always gives me an error that permission already exists, though it doesn't exist in the tenant table but does exist in the main site database table.
PS: I made sure permission cache is cleared before seed

**Comment by stancl** [comment] 2019-12-25 13:55
I'll try to take a look at the demo repo in the next few days.

**Comment by coding-sunshine** [comment] 2020-01-15 08:46
@stancl any help with this possible? I also tried to look into the code but couldn't figure out why this is happening :(

**Comment by stancl** [comment] 2020-01-15 14:03
@coding-sunshine I'm looking at @dathi's repository now. Do you have the same problem or is it just 

> it always gives me an error that permission already exists, though it doesn't exist in the tenant table but does exist in the main site database table.

Also, isn't the issue that the *migration* already exists, rather than the *table* already existing?

**Comment by stancl** [comment] 2020-01-15 14:41
Okay, I can reproduce the issue with `@can`. Changing the Create user permission in the central app affects whether the button is rendered in the tenant app.

The central admin panel writes to central DB, but `@can` seems to use that DB even in the tenant context.

**Comment by stancl** [comment] 2020-01-15 16:04
Setting `permission.cache.store` to `array` (which basically disables the caching mechanism) fixes this. That's of course a very bad fix but it shows that the issue is with permissions being cached.

I'll see if maybe changing the `permission.cache.key` to something specific to the current tenant fixes this.

**Comment by stancl** [comment] 2020-01-15 16:26
Add this to your `AppServiceProvider`'s `boot` method:

```php
tenancy()->hook('bootstrapped', function (TenantManager $tenantManager) {
    \Spatie\Permission\PermissionRegistrar::$cacheKey = 'spatie.permission.cache.tenant.' . $tenantManager->getTenant('id');
});
```

Works for me. If you all can confirm that this fixes the problem for you and doesn't cause other issues, I will add this to docs.

**Comment by dathi** [comment] 2020-01-16 05:36
Great fix. It works properly. Thanks @stancl.

**Comment by stancl** [comment] 2020-01-19 14:26
https://github.com/stancl/tenancy-docs/commit/0ba5f83b840cebac6403cb277017367ecfa558a9

**Closed as completed by stancl** 2020-01-19 14:26 UTC
Labels: documentation
