### ISSUE TITLE
Producing temporary signed URLs from central app for a tenant.

### ISSUE THREAD

**Issue by mdeloughry** [archtechx/tenancy#249] opened 2019-12-17 09:50 UTC
Love the package!

I'm just wondering if anyone has any advice on how to create temporarily signed URLs for a tenant, from inside the central app?

The problem I'm trying to solve is creating a user for a tenant from inside the central app and using https://github.com/spatie/laravel-welcome-notification to send a welcome email. 

I'm able to create the user fine, I've also been able to send out the email but the temporary signed URL is always that of the central app, I've even tried overriding the sending/building of the email to be `inside initaializeTenancy` code block.

eg.
```
        tenancy()->initializeTenancy($this->tenant);

            $this->showWelcomeFormUrl = URL::temporarySignedRoute(
                'welcome', $this->validUntil, ['user' => $this->user->id]
            );

            return (new MailMessage)
                ->subject('Welcome to my app')
                ->action(Lang::get('Set initial password'), $this->showWelcomeFormUrl);

        tenancy()->endTenancy();
```

Any help would be greatly appreciated.

**Comment by sergeByishimo** [comment] 2019-12-17 13:01
Same issue!

**Comment by sergeByishimo** [comment] 2019-12-17 14:52
Some progress!

I intercepted the url before being assigned to the `showWelcomeFormUrl` property in  `WelcomeNotification` and used spatie's url manipulation package [https://github.com/spatie/url](https://github.com/spatie/url) to change the host to the first domain of the current initialized tenant.

but still the generated url is not valid!

i overrided `initializeNotificationProperties` function in my custom welcome notification class
```
    protected function initializeNotificationProperties(User $user)
    {
        $this->user = $user;

        $this->user->welcome_valid_until = $this->validUntil;
        $this->user->save();

        $domain = tenant()->domains[0];


        $signedUrl = URL::temporarySignedRoute(
            'welcome', $this->validUntil, ['user' => $user->id]
        );

        $url = \Spatie\Url\Url::fromString($signedUrl);

        $this->showWelcomeFormUrl = $url->withHost($domain);
    }
```

**Comment by stancl** [comment] 2019-12-17 15:45
Hi,

So the issue is that the `URL::temporarySignedRoute()` method is generating URLs for the central domain?

https://github.com/spatie/laravel-welcome-notification/blob/ccf8b6a9158b90c52386ae53d760d72320838398/src/WelcomeNotification.php#L68-L70

Hmm. Does running something like this

```php
$tenant = ...;

$tenant->run(function () {
    dd(\URL::temporarySignedRoute(...));
});
```

in the central app also result in the domain in the URL being wrong?

You could replace the domains manually but ideally the domain for the URL generator would be correct when the call is wrapped in `$tenant->run()` or `tenancy()->initialize()`.

If you can reproduce this by calling `temporarySignedRoute()` yourself in a `$tenant->run()` block, I'll make the package somehow switch the domain when initializing tenancy.

**Comment by sergeByishimo** [comment] 2019-12-17 15:57
Yes

```
$tenant = ...;

$tenant->run(function () {
    dd(\URL::temporarySignedRoute(...));
});
```
result with the central app domain! 

it seems to not care whether its wrapped in the ` $tenant->run()` or `tenancy()->initialize()`.
you can do a simple test yourself!

**Comment by stancl** [comment] 2019-12-17 16:00
Alright, I'll try to fix this soon.

**Comment by sergeByishimo** [comment] 2019-12-17 16:06
thanks that would help a lot!

**Comment by stancl** [comment] 2019-12-17 17:06
Actually, this is not a bug because the package has no way of knowing which domain it should use when you're calling things from the central domain.

But luckily, Laravel's `UrlGenerator` comes with a `formatHostUsing()` method that accepts a callback letting you return the host used in the generated URLs.

For specific calls, you can do this:

```php
$tenant->run(function (Tenant $tenant) {
    URL::formatHostUsing(function () use ($tenant) {
        return 'https://' . $tenant->domains[0];
    });

    // ...
});
```

Or if you want this to happen automatically (and always for `domains[0]`), you can use the `bootstrapping` hook:

```php
tenancy()->hook('bootstrapping', function (TenantManager $tm, Tenant $tenant) {
    URL::formatHostUsing(function () use ($tenant) {
        return 'https://' . $tenant->domains[0];
    });
});

**Comment by stancl** [comment] 2019-12-17 17:07
I would close this but I think it might be useful to mention this solution in the documentation.

**Comment by sergeByishimo** [comment] 2019-12-18 06:34
that completely solves the issue! thanks for looking out for us! this package is great.

but how come that `formatHostUsing()` method is not even documented in laravel. its only in the api docs and i'm sure some people struggled with it.

**Comment by stancl** [comment] 2019-12-18 06:39
Probably because not many people have a use case for that. When building more complex apps I think people are expected to use both the docs and api docs/source code.

I found the method when looking at the UrlGenerator source code. It's nice that Laravel has it.

**Comment by sergeByishimo** [comment] 2019-12-18 06:49
yeah you are right, and from now on i'll try hard to read the source codes. thanks again! you are a lifesaver!

**Comment by mdeloughry** [comment] 2019-12-18 12:04
I can confirm this solved my issue too, many thanks!!!

**Comment by mdeloughry** [comment] 2019-12-20 10:26
A heads up...

```
tenancy()->hook('bootstrapping', function (TenantManager $tm, Tenant $tenant) {
    URL::formatHostUsing(function () use ($tenant) {
        return 'https://' . $tenant->domains[0];
    });
});
```
It's not quite a simple as just putting this in the `AppServiceProvider.php`'s boot method. This works for the tenants and sending the welcome emails, however, it seems to mess up the central apps `URL` 


Steps to reproduce.
1 - Apply code above into `AppServiceProvider.php` -> `boot()`.
2 - Send out Welcome email from Central app, or do something that initialises the `tenancy()`
3 - The central apps `URL` has now changed to that of the `Tenants` URL regardless.

need to look for a solution that will reset the URL back after finishing with the URL, will update if I find a solution

**Comment by stancl** [comment] 2019-12-20 10:33
Right. Wrapping the specific call in the run block is the only solution then.

**Comment by mdeloughry** [comment] 2019-12-20 10:41
> Right. Wrapping the specific call in the run block is the only solution then.

I'm not entirely sure it is, just testing and this seems to work on inital pass (need to do more testing to be 100% sure).
```
        tenancy()->hook('bootstrapping', function (TenantManager $tm, Tenant $tenant) {
            URL::formatHostUsing(function () use ($tenant) {
                return 'http://' . $tenant->domains[0];
            });
        });

        tenancy()->hook('ending', function (TenantManager $tm, Tenant $tenant) {
            URL::formatHostUsing(function () {
                return config('app.url');
            });
        });
```

**Comment by mdeloughry** [comment] 2019-12-20 13:51
> > Right. Wrapping the specific call in the run block is the only solution then.
> 
> I'm not entirely sure it is, just testing and this seems to work on inital pass (need to do more testing to be 100% sure).
> 
> ```
>         tenancy()->hook('bootstrapping', function (TenantManager $tm, Tenant $tenant) {
>             URL::formatHostUsing(function () use ($tenant) {
>                 return 'http://' . $tenant->domains[0];
>             });
>         });
> 
>         tenancy()->hook('ending', function (TenantManager $tm, Tenant $tenant) {
>             URL::formatHostUsing(function () {
>                 return config('app.url');
>             });
>         });
> ```

Can confirm this works.

**Comment by stancl** [comment] 2019-12-21 12:16
I'm going to add this to the documentation today. Is there any benefit to using the events instead of wrapping the specific call in the `run()` block? It can definitely result in unexpected issues, so I want to know if there are more use cases for changing the `UrlGenerator` host.

**Comment by sergeByishimo** [comment] 2019-12-21 17:12
well, for my case, i used the events bcz i want every url generated while in a tenant to use the first domain of that tenant. and people are creating url so often in their apps, coz even the simple normal `url()` helper function was using the central app domain before we found the solution. 

so i'd for go for the events coz it doesn't even affect the assets urls coz they are alwayz available.

**Comment by stancl** [comment] 2019-12-21 17:29
Unless there is an actual benefit to having the host always changed, I'm not going to encourage it. Arbitrary global state changes are never a good idea. If you can make some change for a single call and it will work, you'll save yourself a massive debugging headache in the future.

**Comment by sergeByishimo** [comment] 2019-12-21 18:16
right, i'm not completely sure, but i don't see anything going wrong as long as we removed the formatted host while the tenant was ending! plus i dont see a better alternative. i'm gonna have to face it.

i think this will work for me.

> ```
>  tenancy()->hook('bootstrapping', function (TenantManager $tm, Tenant $tenant) {
>      URL::formatHostUsing(function () use ($tenant) {
>          return 'http://' . $tenant->domains[0];
>      });
>  });
> 
>  tenancy()->hook('ending', function (TenantManager $tm, Tenant $tenant) {
>      URL::formatHostUsing(function () {
>          return config('app.url');
>      });
>  });
> ```

**Comment by stancl** [comment] 2019-12-21 18:17
> i dont see a better alternative

What's wrong with

```php
$tenant->run(function (Tenant $tenant) {
    URL::formatHostUsing(function () use ($tenant) {
        return 'https://' . $tenant->domains[0];
    });

    // ...
});
```

**Comment by sergeByishimo** [comment] 2019-12-21 18:26
> > i dont see a better alternative
> 
> What's wrong with
> 
> ```
> $tenant->run(function (Tenant $tenant) {
>     URL::formatHostUsing(function () use ($tenant) {
>         return 'https://' . $tenant->domains[0];
>     });
> 
>     // ...
> });
> ```

that's not wrong coming from the central app. i was just saying from a tenant perspective, coz 95% of work in my use case is in the tenant. i think that's actually the best way to do it in the central app.

**Comment by stancl** [comment] 2019-12-21 18:28
Why would you need to change it for the use inside the tenant app? Does `UrlGenerator` not use the current hostname?

**Comment by sergeByishimo** [comment] 2019-12-21 18:53
yes it does, but sometimes you may not be coming from a HTTP request, and i think that's why we are facing this issue. 

For example : using this [spatie/laravel-welcome-notification](https://github.com/spatie/laravel-welcome-notification)  package, i was running my tests while a tenant was initialized but the generated signed url didn't have the tenant domain.

and i'm not sure if, for example, you are sending emails that has tenant specific urls in them from a job, although the job may be tenant-aware, i don't think the  `UrlGenerator` would automatically know the hostname to use. and that's why formatting the host in the hook, comes in handy.

**Comment by sergeByishimo** [comment] 2019-12-21 19:07
but you are also right, you can format the host in the job, but not necessarily globally, and that's actually safer. :thumbsup:

**Comment by stancl** [comment] 2019-12-21 19:10
Hmm, I see. That's a separate issue related to testing though. So I think using the `run()` block for specific calls is safer. And if you have issues while testing, you do something like changing `app.url` config in the `setUp()` method for those tests.

**Comment by sergeByishimo** [comment] 2019-12-21 19:20
>  you do something like changing app.url config in the setUp() method for those tests.

yeah, or just call the `URL::formatHostUsing()` method in your provided test function example `initializeTenancy()`  would also work!

**Comment by sergeByishimo** [comment] 2019-12-21 19:24
> so I want to know if there are more use cases for changing the UrlGenerator host.

i think in your documentation, you just need to make aware of the `URL::formatHostUsing()`. and 
 users will decide where they want to use it.

**Comment by stancl** [comment] 2020-03-12 17:05
I'm not sure if this belongs into the documentation 🤔. I think this issue is pretty discoverable on GitHub so I won't add anything to documentation until another person has this problem and I figure out where to add this to the docs.

**Closed as completed by stancl** 2020-03-12 17:05 UTC
Labels: documentation

**Comment by kaptk2** [comment] 2021-06-30 17:55
I too am facing this issue when trying to use a signed route within a trait. The resulting URL does not contain the hostname. The above solutions do not seem to fix it.

```
trait SignedLinkTrait
{
    public function getLink(User $user, Product $product)
    {
            return URL::temporarySignedRoute('access', now()->addDays(7), [
                'user' => $user->id,
                'product' => $product->id,
            ]);
    }
}
```

**Comment by kaptk2** [comment] 2021-07-05 15:38
Here is what I did to solve it, I moved the route I was trying to access out of my tenant route file and to the central routes file. I then wrapped that route in a group:

```
Route::domain('{tenant}.'.env('APP_DOMAIN'))->group(function () {
   Route::get('/access/{user}/{product}', [AccessController::class, 'product'])->name('access');
})
```

Be sure to change the temporary signed route call to pass in the tenant. 

This isn't a perfect solution if you use both subdomain / domain based tenant identification but for my use case, it works.

**Comment by GarethSomers** [comment] 2021-08-12 05:50
Anyone running into this, I used this code:

```<?php
namespace App\Tenancy\Bootstrappers;

use Stancl\Tenancy\Contracts\TenancyBootstrapper;
use Stancl\Tenancy\Contracts\Tenant;

class FixSignedUrls implements TenancyBootstrapper
{
    public function bootstrap(Tenant $tenant)
    {
        \URL::formatHostUsing(function () use ($tenant) {
            return 'http://' . $tenant->domains->first()->domain;
        });
    }

    public function revert()
    {
        \URL::formatHostUsing(function () {
            return config('app.url');
        });
    }
}
```

And added it as a bootstrapper as described here: https://tenancyforlaravel.com/docs/v3/tenancy-bootstrappers/#writing-custom-bootstrappers

**Comment by bbashy** [comment] 2023-05-30 11:33
Came across this and used @GarethSomers solution but with an extra check for https/http.

```
URL::formatHostUsing(function () use ($tenant) {
    $protocol = request()->isSecure() ? 'https://' : 'http://';
            
    return $protocol.$tenant->domains->first()->domain;
});
```

**Comment by fklee** [comment] 2024-08-22 10:10
Came on this issue too.

Maybe add a note on the documentation, because this arrive as soon as you sens mail through the queue. 
As say @stancl I found the solution directly by internet, but should be better before your application is already in production 
But the method to solve the problem, would different by users.

**Comment by citricguy** [comment] 2024-10-07 18:42
I had a slightly different need, but this seemed to work for me in regards to custom subdomains:

```php
<?php
namespace App\Tenancy\Bootstrappers;

use Illuminate\Support\Facades\URL;
use Stancl\Tenancy\Contracts\Tenant;
use Stancl\Tenancy\Contracts\TenancyBootstrapper;

class FixSignedUrls implements TenancyBootstrapper
{
    public function bootstrap(Tenant $tenant)
    {
        URL::formatHostUsing(function () use ($tenant) {
            $protocol = request()->isSecure() ? 'https://' : 'http://';

            $tenantDomain = $tenant->domains->first()->domain;
            $centralDomains = config('tenancy.central_domains');
            $fullDomain = $tenantDomain.'.'.$centralDomains[0];

            return $protocol.$fullDomain;
        });
    }

    public function revert()
    {
        URL::formatHostUsing(function () {
            return config('app.url');
        });
    }
}
```

Thank you @bbashy & @GarethSomers

**Comment by Illizian** [comment] 2025-04-18 15:07
I'm coming back to this issue now as a result of what I'm seeing as a discrepancy between URL generation within a controller/tenancy context, and a job/tenancy context.

```php
class Foo extends Model
{
    protected static function boot(): void
    {
        parent::boot();
        static::created(function (self $foo) {
            $url_model = URL::temporarySignedRoute('route', now()->addDays(3));
            dump($url_model);
            Job::dispatch(tenant(), $model);
        }
     }
}

class Job implements ShouldQueue
{
    use Queueable;

    public function handle(): void
    {
        dump(tenant());

        $url_job_basic = URL::temporarySignedRoute('route', now()->addDays(3));
        dump($url_job_basic);

        $this->tenant->run(function () {
            $url_tenant_run = URL::temporarySignedRoute('route', now()->addDays(3));
            dump($url_tenant_run);
        });

        $ssl = // ???? - I don't have a Request here
        $url_formatted = URL::formatHostUsing(fn () => 'http://'.$this->tenant->domains()->first()->domain)
            ->temporarySignedRoute('route', now()->addDays(3));
        dump($url_formatted);
    }
}

Foo::create();
```

The output of this, is as follows:

> ✅ $url_model = "http://tenant.localhost/route"
> ✅ tenant() = `<Correct Tenant Model>`
> ❎ $url_job_basic "http://localhost/route"
> ❎ $url_tenant_run "http://localhost/route"
> ﹖ $url_formatted = "http://tenant.localhost/route"

Now, of course, there's a fair few workarounds to this. Including the final one (despite a lack of ssl certainty). I'm still in the process of investigating. I'm a little concerned about other footguns in terms of tenancy jobs though.

**Update:** I have now found that this is the case within Tests too. I have the following Trait that calls initialize prior to testsing, but the URLs generated are local still.

**Update 2:** I am now also realising that this would be difficult to resolve without "knowing" which domain to generate the URL against - tough problem to resolve!! It needs the current request in order to understand the tenant context completely!

**Comment by stancl** [comment] 2025-04-18 15:57
https://github.com/archtechx/tenancy/blob/master/src/Bootstrappers/RootUrlBootstrapper.php

**Comment by Illizian** [comment] 2025-04-20 14:04
> https://github.com/archtechx/tenancy/blob/master/src/Bootstrappers/RootUrlBootstrapper.php

thanks; to confirm this is in the beta v4 branch? I should copy it for now?
