### ISSUE TITLE
No schema has been selected

### ISSUE THREAD

**Issue by Oxbobby** [archtechx/tenancy#608] opened 2021-03-04 15:03 UTC
#### Describe the bug
I get "no schema has been selected" error when trying to **test** creating a tenant through the command line via Laravel Feature tests. This problem occurs on the migrations phase. I use PostgreSQL with schemas, Laravel JSON API. When I try to create a tenant through postman, I succeed without any problems.  Do I have to activate some triggers manually?

#### Steps to reproduce
PostgreSQL, schema multitenancy.
1. Add a json API central route for creating tenants and make it workable.
2. Call `$this->postJson` from a Feature test with destination the route in point 1.

#### Your setup
 - Laravel version: 8.12
 - stancl/tenancy version: 3.4

**Comment by stancl** [comment] 2021-03-04 16:14
If it works in Postman but not in tests, it seems like you have a misconfigured test setup. Try re-reading that part of the docs.

Not a bug with the package, so I'm closing this.

**Closed as completed by stancl** 2021-03-04 16:14 UTC
