### ISSUE TITLE
$tenant->delete() does not delete the database with sqlite in memory database

### ISSUE THREAD

**Issue by GENL** [archtechx/tenancy#498] opened 2020-09-22 13:46 UTC
$tenant->delete() does not delete the database with sqlite in memory database during testing.

The database created in: `base_path('database')` still exists.

Because the database deletion is asynchronous(event) sometimes the database it is not delete yet before the next test.
How is the proper way to delete the tenant's testing databases?

**Comment by GENL** [comment] 2020-09-22 14:16
Sorry. This behavior happens only when `tenancy()->initialize($tenant);` is called in the `setUp` method.

**Comment by stancl** [comment] 2020-09-22 14:46
Hey,

The testing setup is something that's 100% up to you.

The package docs go over the general things you can use in your TestCase to write a setup that works for you. Then there's the setup in the sponsor docs taken from the boilerplate that's more opinionated but works out of the box.

And if you need anything custom, that's completely fine 👍🏻  The idea is to let you build a test suite setup that works for you, because this will differ a lot from app to app.

I'm closing this because it's not a bug related to the package/

Also check my comment here: https://github.com/stancl/tenancy/issues/497#issuecomment-696767720 I'll be building a better test suite, that cleans up databases and uses transactions, soon.

**Closed as completed by stancl** 2020-09-22 14:46 UTC
Labels: bug
