### ISSUE TITLE
Tenant cannot be created when I run my test.

### ISSUE THREAD

**Issue by albatarnik** [archtechx/tenancy#393] opened 2020-05-05 15:26 UTC
#### Describe the bug

I am trying to test up my application, here is the TestCase Class

```
abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;


    public function setUp(): void
    {
        parent::setUp();

        $this->artisan('migrate:fresh');

        config([
            'tenancy.queue_database_creation' => false,
        ]);

        config(['tenancy.exempt_domains' => [
            '127.0.0.1',
            'localhost',
        ]]);
        tenancy()->create('test.localhost');
        tenancy()->init('test.localhost');
    }

    public function tearDown(): void
    {
        config([
            'tenancy.queue_database_deletion' => false,
            'tenancy.delete_database_after_tenant_deletion' => true,
        ]);
        tenancy()->all()->each->delete();

        parent::tearDown();
    }
}
```

My test is
```
 /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testCreateArticle()
    {
        $this->setUp();
        $this->withoutExceptionHandling();
        $article = [
            'title' => 'Sample Article'
        ];
        $response = $this->post('/admin/articles',$article);
        $this->assertDatabaseHas('articles',$article);

        $this->tearDown();
    }
```

I am getting this error: 
```
1) Tests\Feature\ManageArticlesTest::testCreateArticle
Stancl\Tenancy\Exceptions\DomainsOccupiedByOtherTenantException: Tenant cannot be created. Reason: One or more of the tenant's domains are already occupied by another tenant.
```

I am not sure if I am doing something wrong.

#### Your setup
 - Laravel version: 7.9.2
 - stancl/tenancy version: ^2.3
 - Storage driver: DB sqilite

**Comment by stancl** [comment] 2020-05-05 16:07
Not a bug with the package, but might be documented wrong. Will take a look at this once I have some time.

**Comment by stancl** [comment] 2020-08-31 19:24
Testing docs have been rewritten for v3, so I'm closing this.

**Closed as completed by stancl** 2020-08-31 19:24 UTC
Labels: documentation
