### ISSUE TITLE
How to include your own tags in jobs?

### ISSUE THREAD

**Issue by lasselehtinen** [archtechx/tenancy#400] opened 2020-05-17 12:31 UTC
Seems like the tags method is always overwritten by the package. Is there any way to add your own job specific manual tags?

**Comment by stancl** [comment] 2020-05-17 14:34
See this: https://github.com/laravel/framework/pull/29643

Ping @themsaid, on the topic of queues and multi-tenancy. Could you reconsider the PR?

**Comment by lasselehtinen** [comment] 2020-05-18 08:30
Thanks, so seems like there has been a PR open for quite a while. Let's hope it will be merged soon.

**Comment by stancl** [comment] 2020-05-18 08:44
I don't think they plan to add it, since they closed all issues and PRs I opened for that feature.

**Comment by morloderex** [comment] 2020-05-22 15:38
@lasselehtinen @stancl 

I have found the issue laravel/framework#29643 related to why the tags is not present in the `Queue::createPayloadUsing` method. 

The issue is within horizon, and i have created a new PR to fix it https://github.com/laravel/horizon/pull/841.
Once it gets merged we should be able to update the package to look for tags and merge them :)

**Comment by stancl** [comment] 2020-05-30 14:49
Seems like this will be fixed in the next major release of Horizon @morloderex. I think I should for now remove the logic that's setting tags in job payloads and instead provide a trait that people **can** optionally apply on their jobs to see the tenant id in Horizon?

**Comment by stancl** [comment] 2020-06-04 17:44
Resolved in v3.

**Closed as completed by stancl** 2020-06-04 17:44 UTC
Labels: support
